/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parse_df814a3186128e0f8c347cd5e880fdc7/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parse_df814a3186128e0f8c347cd5e880fdc7/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parse_df814a3186128e0f8c347cd5e880fdc7/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  }
}
